-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoCoTcRQN+l6mAXkq
RwQIAa9eBY4E5s6R0kS0O27SNiGgCgYIKoZIzj0DAQehRANCAASuPJk1GBCVCkG8
Uwl/Dor1FK69vvyzLhR/2W1BsJtbtigW+wsgdlvDrkNjLbVtAUdrKLcKrdoAgYEE
Ub0A6Awz
-----END PRIVATE KEY-----